The command 'git gq edit' was added.

diff --git a/bin/git-gq b/bin/git-gq
--- a/bin/git-gq
+++ b/bin/git-gq
@@ -39,7 +39,7 @@ SERIESFILE="$PATCHDIR/series"
 PARENTFILE="$PATCHDIR/parent"
 QUEUEFILE="$TOPPATCHDIR/queue"
 
-ALL_COMMANDS="abort applied backup bashcompletion change-order commands continue delete doc export fold glog goto help import init man new parent pop push qname record refresh restore show unapplied"
+ALL_COMMANDS="abort applied backup bashcompletion change-order commands continue delete doc edit export fold glog goto help import init man new parent pop push qname record refresh restore show unapplied"
 
 # shellcheck disable=SC2001
 ALL_COMMANDS_RX=$(echo "$ALL_COMMANDS" | sed -e 's/ /|/g;s/^/^(/;s/$/)$/')
@@ -497,6 +497,30 @@ function unique_patch_name {
     echo "$TEMP_PATCHNAME"
 }
 
+function editor_dialog {
+    # return name of the editor program
+    # returns: 
+    #   the editor
+    #   <empty string> : in case of an error
+    local editor
+    editor="$EDITOR"
+    if [ -z "$EDITOR" ]; then
+        editor="$VISUAL"
+    fi
+    if [ -z "$editor" ]; then
+        echo "Caution: No default editor is specified in environment "
+        echo "variables 'EDITOR' and 'VISUAL'."
+        echo "Use 'vi' instead ?"
+        echo "Note that you can always abort editing in 'vi' with"
+        echo "  <ESC> :qa!"
+        read -p "Enter 'y' or 'Y' to continue, everything else aborts " -n 1 -r
+        if [[ $REPLY =~ ^[Yy]$ ]]; then
+            editor="vi"
+        fi
+    fi
+    echo "$editor"
+}
+
 function prepend_seriesfile {
     # prepend a filename to the series file
     # $1: filename
@@ -924,6 +948,28 @@ function qpush_one {
     rm -f "$PATCHDIR/$PATCHNAME" "$PATCHDIR/PUSH" "$SERIESFILE" && mv "$SERIESFILE.new" "$SERIESFILE"
 }
 
+function qedit {
+    # $1: name of patch to edit
+    # returns: 
+    #   0 : no error
+    #   1 : fatal error
+    # in case of an error, the function prints an error message to stderr.
+    local name
+    local patchname
+    local rc
+    name="$1"
+    editor=$(editor_dialog)
+    if [ -z "$editor" ]; then
+        return 1
+    fi
+    patchname=$(find_single_unapplied_patch "$name")
+    rc="$?"
+    if [ "$rc" -ne 0 ]; then
+        return "$rc"
+    fi
+    $editor "$PATCHDIR/$patchname"
+}
+
 function qdelete {
     # $1: name of patch to delete
     # returns: 
@@ -1057,6 +1103,9 @@ Patch management commands
     already. Note that the log message of the fold-patch is appended to the
     existing log message. You may change the log message with \`$MYNAME_GIT
     refresh -e\`.
+
+  edit NAME|REGEXP
+    Call an editor to edit an unapplied patch. 
 
   delete NAME|REGEXP
     Delete unapplied patch with given name.
@@ -1277,7 +1326,7 @@ for arg in "${ARGS[@]}"; do
         echo "unexpected: '$arg'" >&2
         exit 1
     fi
-    if [[ "$COMMAND" =~ qname|fold|goto|new|record|delete|show ]]; then
+    if [[ "$COMMAND" =~ qname|fold|goto|new|record|edit|delete|show ]]; then
         if [ -n "$name_arg" ]; then
             echo "unexpected: '$arg'" >&2
             exit 1
@@ -1460,21 +1509,9 @@ if [ "$COMMAND" == "backup" ]; then
 fi
 
 if [ "$COMMAND" == "change-order" ]; then
-    editor="$EDITOR"
-    if [ -z "$EDITOR" ]; then
-        editor="$VISUAL"
-    fi
-    if [ -z "$EDITOR" ]; then
-        echo "Caution: No default editor is specified in environment "
-        echo "variables 'EDITOR' and 'VISUAL'."
-        echo "Use 'vi' instead ?"
-        echo "Note that you can always abort editing in 'vi' with"
-        echo "  <ESC> :qa!"
-        read -p "Enter 'y' or 'Y' to continue, everything else aborts " -n 1 -r
-        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-            exit 1
-        fi
-        editor="vi"
+    editor=$(editor_dialog)
+    if [ -z "$editor" ]; then
+        exit 1
     fi
     $editor "$SERIESFILE"
     exit 0
@@ -1590,6 +1627,17 @@ if [ "$COMMAND" == "refresh" ]; then
         git_rm_changes_files
     fi
     rm -f "$PATCHDIR/LOG"
+    exit 0
+fi
+
+if [ "$COMMAND" == "edit" ]; then
+    if [ -z "$name_arg" ]; then
+        echo "error, patchname is missing" >&2
+        exit 1
+    fi
+    if ! qedit "$name_arg"; then
+        exit 1
+    fi
     exit 0
 fi
 
