Option --lines limits the no. of lines printed by 'git gq applied/unapplied'.
Also 'got gq goto' can now use long hash keys.

diff --git a/bin/git-gq b/bin/git-gq
--- a/bin/git-gq
+++ b/bin/git-gq
@@ -53,6 +53,7 @@ no_add_opt=""
 edit_opt=""
 message_opt=""
 file_opt=""
+lines_opt=""
 full_opt=""
 
 rev_arg=""
@@ -210,6 +211,15 @@ The parent revision is stored in a file 'parent'. This is the latest commit
 that is not allowed to be modified. This file is usually created when you start
 your work with \`$MYNAME_GIT init\`. It can be changed with \`$MYNAME_GIT
 parent\`.
+
+A special revision is \`NULL\`. This is the very first revision in the
+repository where no files are committed. git doesn't have a concept of a
+\`NULL\` revision, so this is emulated by \`$MYNAME_GIT\` by creating a
+revision with no files in it. When the parent is set to \`NULL\` this means
+that you can pop the very first revision as a patch and by this have the
+capability to modify the very first revision. Of course, you should never do
+this with a published repository, since \`$MYNAME_GIT pop\` and \`$MYNAME_GIT
+push\` always modify revision hash keys.
 
 patch files '\*.patch'
 ::::::::::::::::::::::
@@ -598,8 +608,8 @@ function log_template {
     fi
 }
 
-function git_head_full_log {
-    # create file with HEAD log message.
+function make_head_logfile {
+    # create or append file with HEAD log message.
     # $1: filename to create
     # $2: if non-zero, put preamble in the first line
     rm -f "$1"
@@ -607,16 +617,38 @@ function git_head_full_log {
     if [ -n "$2" ]; then
         echo "*** Please review and change this log message" >> "$1"
     else
-        git log --format=%B -1 >> "$1"
+        git_head_log >> "$1"
     fi
 }
 
 function git_oneline_log {
-    # $1: revision spec
+    # $1: revision spec, 'NULL' for *all* revisions
+    # $2: max. number of lines or empty
     # prints one-line log, possible with color, to the console
+    # a bash array is the correct way to provide several extra arguments to a
+    # command:
+    EXTRA=()
     # GIT_PAGER=cat: do not use pager
+    if [ -n "$2" ]; then
+        EXTRA+=("-${2}")
+    fi
+    if [ "$1" != "NULL" ]; then
+        EXTRA+=("${1}..")
+    fi
     # shellcheck disable=SC2209
-    GIT_PAGER=cat git log --color=auto --oneline "$1"
+    GIT_PAGER=cat git log --color=auto --oneline "${EXTRA[@]}" 
+}
+
+function git_format_patch {
+    # $1: revision spec, 'NULL' for *all* revisions
+    # $2: output directory
+    local EXTRA
+    if [ "$1" == "NULL" ]; then
+        EXTRA="--root"
+    else
+        EXTRA="${1}.."
+    fi
+    git format-patch -o "$2" "$EXTRA"
 }
 
 function git_oneline_log_single {
@@ -658,9 +690,11 @@ function get_parent {
         return 1
     fi
     PARENT="$(cat "$PARENTFILE")"
-    if ! git_check_exists "$PARENT"; then
-        echo "Error, parent revision $PARENT doesn't exist in repository" >&2
-        return 1
+    if [ "$PARENT" != "NULL" ]; then
+        if ! git_check_exists "$PARENT"; then
+            echo "Error, parent revision $PARENT doesn't exist in repository" >&2
+            return 1
+        fi
     fi
     echo "$PARENT"
     return 0
@@ -695,7 +729,7 @@ function find_single_unapplied_patch {
 }
 
 function find_first_unapplied_patch {
-    # $1: regexp
+    # $1: regexp or empty string
     # finds unapplied patch
     # returns:
     #  the patch
@@ -705,32 +739,10 @@ function find_first_unapplied_patch {
         echo ""
         return
     fi
-    grep "$1" "$SERIESFILE" | head -n 1
-}
-
-function find_first_applied_patch {
-    # $1: regexp
-    # finds applied patch, returns hash key
-    # returns: 
-    #   0 : no error
-    #   1 : fatal error
-    # in case of an error, the function prints an error message to stderr.
-    local START
-    local PARENT
-    local RX
-    RX="$1"
-    PARENT=$(get_parent)
-    rc="$?"
-    if [ "$rc" -ne 0 ]; then
-        return "$rc"
-    fi
-    START="${PARENT}.."
-    if echo "$RX" | grep -q '^[A-Fa-f0-9]\+$'; then
-        # a pure hash key, use log with long hash keys to match
-        git log --pretty=oneline "$START" | grep "^$RX" | head -n 1 | sed -e 's/ .*//'
+    if [ -z "$1" ]; then
+        head -n 1 "$SERIESFILE"
     else
-        # common search for strings
-        git log --oneline "$START" | grep "$RX" | head -n 1 | sed -e 's/ .*//'
+        grep "$1" "$SERIESFILE" | head -n 1
     fi
 }
 
@@ -749,9 +761,54 @@ function git_rev_parse {
     echo "$REV"
 }
 
+function find_first_applied_patch {
+    # $1: regexp
+    # finds applied patch, returns hash key
+    # returns: 
+    #   0 : no error
+    #   1 : fatal error
+    # in case of an error, the function prints an error message to stderr.
+    local PARENT
+    local RX
+    local EXTRA
+    local HASH
+    RX="$1"
+    PARENT=$(get_parent)
+    rc="$?"
+    if [ "$rc" -ne 0 ]; then
+        return "$rc"
+    fi
+    # a bash array is the correct way to provide several extra arguments to a
+    # command:
+    EXTRA=()
+    if [ "$PARENT" != "NULL" ]; then
+        EXTRA+=("${PARENT}..")
+    fi
+    if echo "$RX" | grep -q '^[A-Fa-f0-9]\+$'; then
+        # a pure hash key, use log with long hash keys to match
+        HASH=$(git log --pretty=oneline "${EXTRA[@]}" | grep "^$RX" | head -n 1 | sed -e 's/ .*//')
+    else
+        # common search for strings
+        HASH=$(git log --oneline "${EXTRA[@]}" | grep "$RX" | head -n 1 | sed -e 's/ .*//')
+    fi
+    if [ -z "$HASH" ]; then
+        echo ""
+    else
+        # return shortened hash
+        # Note: this MUST be compatible with git_head_revision
+        # 'git gq goto' breaks if we use different hash key lengths.
+        git_rev_parse "$HASH"
+    fi
+}
+
 function git_head_revision {
     # returns revision of HEAD
     git rev-parse --short HEAD
+}
+
+function git_revision_1 {
+    # returns hash of first revision.
+    git rev-list --max-parents=0 --format='%h' HEAD | tail -n 1
 }
 
 function find_head_patch {
@@ -773,9 +830,34 @@ function dump_patch_file {
 }
 
 function git_head_log {
-    # Get the pure log message of the HEAD patch.
+    # Get the pure full log message of the HEAD patch.
     # print to stdout
     git log -1 --pretty=%B 
+}
+
+function git_head_subject {
+    # Get the pure log message of the HEAD patch.
+    # print to stdout
+    git log -1 --pretty=%s 
+}
+
+function git_head_date {
+    # Get the commit date as ISO date
+    # print to stdout
+    git log -1 --pretty=%aI
+}
+
+function git_head_author {
+    # Get the commit date as ISO date
+    # print to stdout
+    git log -1 --pretty='%aN <%aE>'
+}
+
+function at_null_revision {
+    # returns: 
+    #   0 : HEAD is a NULL revision
+    #   1 : HEAD is not a NULL revision
+    git_head_subject | grep -w -q 'NULL'
 }
 
 function git_add_changes {
@@ -817,6 +899,8 @@ function git_amend {
     # $1: if not empty, take log message from this file
     # $2: if not empty, take log message from $1 as a template the 
     #     user has to edit
+    # $3: if not empty, take date from here
+    # $4: if not empty, take author from here
     local EXTRA
     # a bash array is the correct way to provide several extra arguments to a
     # command:
@@ -825,6 +909,12 @@ function git_amend {
         EXTRA+=("-t" "$1")
     elif [ -n "$1" ]; then
         EXTRA+=("-F" "$1")
+    fi
+    if [ -n "$3" ]; then
+        EXTRA+=("--date=$3")
+    fi
+    if [ -n "$4" ]; then
+        EXTRA+=("--author=$4")
     fi
     git commit --amend "${EXTRA[@]}"
 }
@@ -836,6 +926,7 @@ function save_applied_patches {
     #   1 : fatal error
     # in case of an error, the function prints an error message to stderr.
     local PARENT
+    local EXTRA
     local rev
     PARENT=$(get_parent)
     rc="$?"
@@ -846,7 +937,7 @@ function save_applied_patches {
     rm -rf "$APPLIEDDIR"
     if [ "$rev" != "$PARENT" ]; then
         mkdir -p "$APPLIEDDIR"
-        git format-patch -o "$APPLIEDDIR" "$PARENT.."
+        git_format_patch "$PARENT" "$APPLIEDDIR"
     fi
 }
 
@@ -888,6 +979,14 @@ function qpop_check {
     if [ "$rc" -ne 0 ]; then
         return 2
     fi
+    if [ "$PARENT" == "NULL" ]; then 
+        # with PARENT==NULL, qpop is always allowed
+        if at_null_revision; then
+            # NULL revision reached
+            return 1
+        fi
+        return 0
+    fi
     rev=$(git_head_revision)
     if [ "$PARENT" == "$rev" ]; then
         return 1
@@ -901,6 +1000,8 @@ function qpop_one {
     local PATCHNAME
     local TEMP_PATCHNAME
     local CNT
+    local HEADREV
+    local REV1
     ORIG_PATCHNAME=$(git format-patch -o "$TOPPATCHDIR" -1 HEAD | sed -e "s#^$TOPPATCHDIR/##")
     # remove leading number from patchname:
     # shellcheck disable=SC2001
@@ -909,7 +1010,16 @@ function qpop_one {
     PATCHNAME="$(unique_patch_name "$PATCHNAME")"
     mv "$TOPPATCHDIR/$ORIG_PATCHNAME" "$PATCHDIR/$PATCHNAME"
     prepend_seriesfile "$PATCHNAME"
-    git reset --hard HEAD~1
+    HEADREV="$(git_head_revision)"
+    REV1="$(git_revision_1)"
+    if [ "$HEADREV" == "$REV1" ]; then
+        # special treatment for first revision, create a "zero revision" patch
+        # by deleting all files and amend the first patch accordingly:
+        git rm -r '*'
+        git commit --amend -m 'NULL' --reset-author  --allow-empty
+    else
+        git reset --hard HEAD~1
+    fi
 }
 
 function qpush_specified {
@@ -1016,16 +1126,21 @@ function create_parentfile {
     #   1 : fatal error
     # in case of an error, the function prints an error message to stderr.
     local rev
-    rev=$(git rev-parse --short "$1")
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo "Error, invalid revision: $1" >&2
-        return 1
-    fi
-    if [ "$1" == "$rev" ]; then
+    if [ "$1" == "NULL" ]; then
         echo "queue parent revision set to $1"
+        rev="$1"
     else
-        echo "queue parent revision set to $1 ($rev)"
+        rev=$(git rev-parse --short "$1")
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then
+            echo "Error, invalid revision: $1" >&2
+            return 1
+        fi
+        if [ "$1" == "$rev" ]; then
+            echo "queue parent revision set to $1"
+        else
+            echo "queue parent revision set to $1 ($rev)"
+        fi
     fi
     echo "$rev" > "$PARENTFILE"
 }
@@ -1081,7 +1196,10 @@ Queue management commands
   parent [REVISION}   
     Set REVISION as patch queue parent revision. Do never go beyond this
     revision with pop. Use 'HEAD' to set your repository HEAD as parent
-    revision. If HEAD is not given, show the current parent revision.
+    revision. If REVISION is 'NULL', this means that *all* revisions in
+    the repository can be managed with \`$MYNAME_GIT pop\`, you should only
+    use this for unpublished repositories. If REVISION is not given, show the
+    current parent revision.
 
   export DIRECTORY
     Create numbered patch files from all currently applied patches in
@@ -1185,6 +1303,10 @@ OPTIONS
   -F --file FILE
     refresh: take log message from FILE.
 
+  -l --lines LINECOUNT
+    applied, unapplied: Limit the number of lines printed by the command. Print
+    only the first LINECOUNT lines.
+
   -L --full
     restore: do also restore all patches that were applied when the backup was
     created. Caution: This runs \`git checkout PARENT\` and \`git am\` on your
@@ -1251,6 +1373,14 @@ while true; do
             ;;
         -F | --file)
             file_opt="$2"
+            shift 2
+            ;;
+        -l | --lines)
+            lines_opt="$2"
+            if ! echo "$lines_opt" | grep -q '^[0-9]\+$'; then
+                echo "Error, the --lines argument must be a positive integer." >&2
+                exit 1
+            fi
             shift 2
             ;;
         -D | --debug)
@@ -1442,6 +1572,12 @@ if [ "$COMMAND" == "restore" ]; then
     if [ "$rc" -ne 0 ]; then
         exit "$rc"
     fi
+    if [ "$PARENT" == "NULL" ]; then
+        echo "Your PARENT revision was NULL."
+        echo "Cannot automatically restore applied patches."
+        echo "Originally applied patches are in $APPLIEDDIR"
+        exit 0
+    fi
     if [ -n "$full_opt" ] && [ -d "$APPLIEDDIR" ]; then
         echo "Restore originally applied patches in repository ?"
         read -p "Enter 'y' or 'Y' to make changes, everything else skips this " -n 1 -r
@@ -1547,8 +1683,7 @@ if [ "$COMMAND" == "export" ]; then
     if [ "$rc" -ne 0 ]; then
         exit "$rc"
     fi
-    START="${PARENT}.."
-    git format-patch -o "$dir_arg" "$START"
+    git_format_patch "$PARENT" "$dir_arg"
     exit 0
 fi
 
@@ -1581,7 +1716,11 @@ if [ "$COMMAND" == "parent" ]; then
             if [ "$rc" -ne 0 ]; then
                 exit "$rc"
             fi
-            git_oneline_log_single "$PARENT"
+            if [ "$PARENT" == "NULL" ]; then
+                echo "NULL"
+            else
+                git_oneline_log_single "$PARENT"
+            fi
         fi
         exit 0
     fi
@@ -1628,7 +1767,7 @@ fi
 
 if [ "$COMMAND" == "refresh" ]; then
     if [ -z "$message_opt" ] && [ -z "$file_opt" ]; then
-        git_head_full_log "$PATCHDIR/LOG" "$edit_opt"
+        make_head_logfile "$PATCHDIR/LOG" "$edit_opt"
     else
         log_template "$message_opt" "$file_opt" "$PATCHDIR/LOG" "$edit_opt" 
     fi
@@ -1641,7 +1780,7 @@ if [ "$COMMAND" == "refresh" ]; then
         # log message:
         git_mk_changes_files "both"
     fi
-    git_amend "$PATCHDIR/LOG" "$edit_opt"
+    git_amend "$PATCHDIR/LOG" "$edit_opt" "" ""
     if [ -n "$edit_opt" ]; then
         # remove the changes files:
         git_rm_changes_files
@@ -1695,9 +1834,30 @@ if [ "$COMMAND" == "pop" ]; then
 fi
 
 if [ "$COMMAND" == "push" ]; then
+    if at_null_revision; then
+        null_revision="yes"
+    else
+        null_revision=""
+    fi
     while true; do
         if ! qpush_one; then
             exit 1
+        fi
+        if [ -n "$null_revision" ]; then
+            # must convert 'push' into a 'fold'
+            git_head_log > "$PATCHDIR/LOG"
+            git_head_date > "$PATCHDIR/DATE"
+            git_head_author > "$PATCHDIR/AUTHOR"
+            qpop_one
+            patchname=$(find_first_unapplied_patch "")
+            git apply "$PATCHDIR/$patchname"
+            # "yes": do also add unknown files since we are at the NULL
+            # revision:
+            git_add_changes "yes"
+            git_amend "$PATCHDIR/LOG" "" "$(cat "$PATCHDIR/DATE")" "$(cat "$PATCHDIR/AUTHOR")"
+            #rm -f "$PATCHDIR/LOG" "$PATCHDIR/DATE" "$PATCHDIR/AUTHOR"
+            qdelete "$patchname"
+            null_revision=""
         fi
         if [ -z "$all_opt" ]; then
             break
@@ -1707,6 +1867,7 @@ if [ "$COMMAND" == "push" ]; then
                 break
             fi
         fi
+        null_revision=""
     done
     exit 0
 fi
@@ -1756,7 +1917,11 @@ if [ "$COMMAND" == "fold" ]; then
         fi
         name_arg="$patchname"
     fi
-    git_head_full_log "$PATCHDIR/LOG" "$edit_opt"
+    if at_null_revision; then
+        echo "Error, cannot fold to 'NULL' revision, use '$MYNAME_GIT push' instead." >&2
+        exit 1
+    fi
+    make_head_logfile "$PATCHDIR/LOG" "$edit_opt"
     echo -e '\n***\n' >> "$PATCHDIR/LOG"
     if ! qpush_specified "$name_arg"; then
         exit 1
@@ -1765,8 +1930,12 @@ if [ "$COMMAND" == "fold" ]; then
     qpop_one
     git apply "$PATCHDIR/$name_arg"
     if [ -z "$no_add_opt" ]; then
-        # "": do not add unknown files:
-        git_add_changes ""
+        # "": do not add unknown files unless we are at the NULL revision:
+        if at_null_revision; then
+            git_add_changes "yes"
+        else
+            git_add_changes ""
+        fi
     fi
     if [ -n "$edit_opt" ]; then
         # create two files so the user can review changes while editing the
@@ -1775,7 +1944,7 @@ if [ "$COMMAND" == "fold" ]; then
     fi
     # if $edit_opt is not empty, git_amend will start an editor to edit the
     # combination of both log messages:
-    git_amend "$PATCHDIR/LOG" "$edit_opt"
+    git_amend "$PATCHDIR/LOG" "$edit_opt" "" ""
     if [ -n "$edit_opt" ]; then
         # remove the changes files:
         git_rm_changes_files
@@ -1829,14 +1998,17 @@ if [ "$COMMAND" == "applied" ]; then
     if [ "$rc" -ne 0 ]; then
         exit "$rc"
     fi
-    START="${PARENT}.."
-    git_oneline_log "$START"
+    git_oneline_log "$PARENT" "$lines_opt"
     exit 0
 fi
 
 if [ "$COMMAND" == "unapplied" ]; then
     if [ -s "$SERIESFILE" ]; then
-        cat "$SERIESFILE"
+        if [ -z "$lines_opt" ]; then
+            cat "$SERIESFILE"
+        else
+            head -n "$lines_opt" "$SERIESFILE"
+        fi
     fi
     exit 0
 fi
