gq.sh was renamed to gq, all commands no longer require 'q' at the start.

diff --git a/gq b/gq
--- a/gq
+++ b/gq
@@ -14,9 +14,11 @@ SERIESFILE="$PATCHDIR/series"
 PARENTFILE="$PATCHDIR/parent"
 QUEUEFILE="$TOPPATCHDIR/queue"
 
-ALL_COMMANDS="completion qabort qapplied qbackup qcontinue qdelete qfold qinit qname qnew qparent qpop qpush qrecord qrefresh qunapplied"
+ALL_COMMANDS="completion abort applied backup continue delete fold init name new parent pop push record refresh unapplied"
 
-ALL_COMMANDS_RX=$(echo "$ALL_COMMANDS" | sed -e 's/ /|/g')
+ALL_COMMANDS_Q=$(echo "$ALL_COMMANDS" | sed -e 's/\</q/g')
+
+ALL_COMMANDS_RX=$(echo "$ALL_COMMANDS $ALL_COMMANDS_Q" | sed -e 's/ /|/g')
 
 verbose=""
 dryrun=""
@@ -117,7 +119,7 @@ function select_queue {
 }
 
 function qpop_check {
-    # returns 0 if qpop is not beyond qparent,
+    # returns 0 if qpop is not beyond parent,
     # returns 1 when qpop is not allowed.
     # $1: if non-zero, instead of returning 1 abort with an error message
     CMDRET "git rev-parse --short HEAD"
@@ -161,9 +163,9 @@ function qpush_specified {
         echo "The patch to be folded could not be applied."
         echo "Fix the change by looking at the *.rej files."
         echo "Then run:"
-        echo "  $MYNAME qcontinue"
+        echo "  $MYNAME continue"
         echo "To abort the operation without fixing run:"
-        echo "  $MYNAME qabort"
+        echo "  $MYNAME abort"
         exit 1
     fi
     CMD "cp -a $SERIESFILE.new $SERIESFILE && rm -f $SERIESFILE.new $PATCHDIR/NEW"
@@ -181,9 +183,9 @@ function qpush_one {
     if [ "$cmdret" -ne 0 ]; then
         echo "Fix the change by looking at the *.rej files."
         echo "Then run:"
-        echo "  $MYNAME qcontinue"
+        echo "  $MYNAME continue"
         echo "To abort the operation without fixing run:"
-        echo "  $MYNAME qabort"
+        echo "  $MYNAME abort"
         exit 1
     fi
     CMD "cp -a $SERIESFILE.new $SERIESFILE && rm -f $SERIESFILE.new $PATCHDIR/NEW"
@@ -217,31 +219,34 @@ function print_short_help {
   echo "  completion    : print bash completion code. Activate completion in your"
   echo "                  shell with:"
   echo "                  eval ($MYNAME completion)"
-  echo "  qinit [NAME]  : create/select a patch queue with name 'NAME'."
+  echo "  init [NAME]   : create/select a patch queue with name 'NAME'."
   echo "                  This is optional, the default patch queue is named"
   echo "                  'default'."
   echo "                  You must run this command once to initialize the"
   echo "                  patch queue."
-  echo "  qname         : show current patch queue name."
-  echo "  qnew [NAME]   : create new patch (commit with log-message NAME)"
-  echo "  qrecord [NAME]: interactively select changes for a new patch"
+  echo "  name          : show current patch queue name."
+  echo "  new [NAME]    : create new patch (commit with log-message NAME)"
+  echo "  record [NAME] : interactively select changes for a new patch"
   echo "                  (commit with log-message NAME)"
-  echo "  qrefresh      : update the topmost patch"
-  echo "  qpop          : pop the topmost patch."
-  echo "  qpush         : apply the top patch from the patch queue"
-  echo "  qparent [REV} : set REV as patch queue parent revision. Do never go "
-  echo "                  beyond this revision with qpop. The default for REV"
+  echo "  refresh       : update the topmost patch"
+  echo "  pop           : pop the topmost patch."
+  echo "  push          : apply the top patch from the patch queue"
+  echo "  parent [REV}  : set REV as patch queue parent revision. Do never go "
+  echo "                  beyond this revision with pop. The default for REV"
   echo "                  is 'HEAD'."
-  echo "  qfold NAME    : fold patch 'NAME' to the topmost patch. Patch 'name'"
+  echo "  fold NAME     : fold patch 'NAME' to the topmost patch. Patch 'name'"
   echo "                  must not be appled already."
-  echo "  qdelete NAME  : delete unapplied patch with given name."
-  echo "  qcontinue     : continue 'qpush' after you had a conflict and had"
+  echo "  delete NAME   : delete unapplied patch with given name."
+  echo "  continue      : continue 'push' after you had a conflict and had"
   echo "                  it fixed manually."
-  echo "  qabort        : abort (undo) 'qpush' after you had a conflict and could"
+  echo "  abort         : abort (undo) 'push' after you had a conflict and could"
   echo "                  not fix it manually."
-  echo "  qapplied      : show all applied patches up to parent+1"
-  echo "  qunapplied    : show all patches of the patch queue"
-  echo "  qbackup       : create backup tar file of patch directory."
+  echo "  applied       : show all applied patches up to parent+1"
+  echo "  unapplied     : show all patches of the patch queue"
+  echo "  backup        : create backup tar file of patch directory."
+  echo
+  echo "For compatibility with mercurial patch queue commands, all commands con"
+  echo "also be prepended with the letter 'q', for example 'qnew' instead of 'new'."
   echo
   echo "options:"
   echo "-h --help  : this help"
@@ -320,7 +325,7 @@ for arg in "${ARGS[@]}"; do
     # if [ "§arg" == "doit" ]; then ...
     #     continue
     # fi
-    if [ "$COMMAND" == "qparent" ]; then
+    if [ "$COMMAND" == "parent" ]; then
         if [ -n "$rev" ]; then
             echo "unexpected: '$arg'" >&2
             exit 1
@@ -328,7 +333,7 @@ for arg in "${ARGS[@]}"; do
         rev="$arg"
         continue
     fi
-    if [[ "$COMMAND" =~ qinit|qfold|qnew|qrecord|qdelete ]]; then
+    if [[ "$COMMAND" =~ init|fold|new|record|delete ]]; then
         if [ -n "$name" ]; then
             echo "unexpected: '$arg'" >&2
             exit 1
@@ -341,7 +346,7 @@ for arg in "${ARGS[@]}"; do
             echo "unexpected: '$arg'" >&2
             exit 1
         fi
-        COMMAND="$arg";
+        COMMAND="$(echo "$arg" | sed -e 's/\<q//')"
         continue
     fi
     echo "unexpeced argument: $arg"
@@ -349,7 +354,7 @@ for arg in "${ARGS[@]}"; do
 done
 
 if [ "$COMMAND" == "completion" ]; then
-    echo "complete -W \"$ALL_COMMANDS\" $MYNAME"
+    echo "complete -W \"$ALL_COMMANDS $ALL_COMMANDS_Q\" $MYNAME"
     exit 0
 fi
 
@@ -358,7 +363,7 @@ if [ ! -d .git ]; then
     exit 1
 fi
 
-if [ "$COMMAND" == "qinit" ]; then
+if [ "$COMMAND" == "init" ]; then
     if [ -n "$name" ]; then
         QUEUENAME="$name"
     fi
@@ -373,7 +378,7 @@ if [ "$COMMAND" == "qinit" ]; then
 fi
 
 if [ ! -d "$TOPPATCHDIR" ]; then
-    echo "please run '$MYNAME qinit' first." >&2
+    echo "please run '$MYNAME init' first." >&2
     exit 1
 fi
 
@@ -383,7 +388,7 @@ if [ ! -d "$PATCHDIR" ]; then
 fi
 select_queue "$QUEUENAME"
 
-if [ "$COMMAND" == "qname" ]; then
+if [ "$COMMAND" == "name" ]; then
     echo "Exissting queues:"
     CMD "cd $TOPPATCHDIR && ls -d */ | sed -e 's#/##;s/^/\\t/'"
     echo
@@ -392,13 +397,13 @@ if [ "$COMMAND" == "qname" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qbackup" ]; then
+if [ "$COMMAND" == "backup" ]; then
     date_=$(date '+%Y-%m-%dT%H%M%S')
     CMD "tar -czf $TOPPATCHDIR-$date_.tgz $TOPPATCHDIR"
     exit 0
 fi
 
-if [ "$COMMAND" == "qparent" ]; then
+if [ "$COMMAND" == "parent" ]; then
     if [ -z "$rev" ]; then 
         rev="HEAD"
         exit 1
@@ -407,7 +412,7 @@ if [ "$COMMAND" == "qparent" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qnew" ]; then
+if [ "$COMMAND" == "new" ]; then
     git_add_changes
     if [ -n "$name" ]; then
         name="-m '$name'"
@@ -416,7 +421,7 @@ if [ "$COMMAND" == "qnew" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qrecord" ]; then
+if [ "$COMMAND" == "record" ]; then
     git_select_changes
     if [ -n "$name" ]; then
         name="-m '$name'"
@@ -425,12 +430,12 @@ if [ "$COMMAND" == "qrecord" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qrefresh" ]; then
+if [ "$COMMAND" == "refresh" ]; then
     git_amend ""
     exit 0
 fi
 
-if [ "$COMMAND" == "qdelete" ]; then
+if [ "$COMMAND" == "delete" ]; then
     if [ -z "$name" ]; then
         echo "error, patchname is missing" >&2
         exit 1
@@ -439,7 +444,7 @@ if [ "$COMMAND" == "qdelete" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qpop" ]; then
+if [ "$COMMAND" == "pop" ]; then
     abort_on_err=""
     if [ -z "$all" ]; then
         abort_on_err="yes"
@@ -456,7 +461,7 @@ if [ "$COMMAND" == "qpop" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qpush" ]; then
+if [ "$COMMAND" == "push" ]; then
     while true; do
         if [ ! -s $SERIESFILE ]; then
             break
@@ -469,7 +474,7 @@ if [ "$COMMAND" == "qpush" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qfold" ]; then
+if [ "$COMMAND" == "fold" ]; then
     if [ -z "$name" ]; then
         echo "error, patchname is missing" >&2
         exit 1
@@ -488,7 +493,7 @@ if [ "$COMMAND" == "qfold" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qapplied" ]; then
+if [ "$COMMAND" == "applied" ]; then
     if [ -s $PARENTFILE ]; then
         CMDRET "cat $PARENTFILE"
         START="${cmddata}.."
@@ -497,14 +502,14 @@ if [ "$COMMAND" == "qapplied" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qunapplied" ]; then
+if [ "$COMMAND" == "unapplied" ]; then
     if [ -s $SERIESFILE ]; then
         CMD "cat $SERIESFILE"
     fi
     exit 0
 fi
 
-if [ "$COMMAND" == "qcontinue" ]; then
+if [ "$COMMAND" == "continue" ]; then
     CMD "git status --porcelain | sed -e 's/^.. //' | grep -v '\(^$PATCHDIR/\|\.rej$\)'| xargs git add"
     CMD "git am --continue"
     if [ "$cmdret" -ne 0 ]; then
@@ -518,13 +523,13 @@ if [ "$COMMAND" == "qcontinue" ]; then
     exit 0
 fi
 
-if [ "$COMMAND" == "qabort" ]; then
+if [ "$COMMAND" == "abort" ]; then
     CMD "git am --abort"
     CMD "rm -f $SERIESFILE.new"
     exit 0
 fi
 
-if [ "$COMMAND" == "qcontinue" ]; then
+if [ "$COMMAND" == "continue" ]; then
     git_add_all_changes
     CMD "git am --continue"
     if [ "$cmdret" -ne 0 ]; then
